-- TRIGGER TP CHECK WHETHER EMPLOYEE CODE EXISTS
CREATE OR REPLACE TRIGGER salary_updated_check
BEFORE INSERT ON EMP_TABLE
FOR EACH ROW
begin
  IF :NEW.EMP_CODE = :OLD.EMP_CODE THEN
    raise_application_error(-201111, 'VIOLATION');
    END IF;
end;
-- TEST CASE FOR TRIGGER 
INSERT INTO EMP_TABLE VALUES('E010', 'MUNEZERO', 'ANGE', 1000000, 'RWANDA');