CREATE TABLE EMPLOYEES(
    ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 5),
    NAME VARCHAR(20),
    SALARY FLOAT
);
insert into EMPLOYEES (Name, SALARY) values ('MUNEZERO', 5000);
insert into EMPLOYEES (Name, SALARY) values ('MBARUSHIMANA', 3000);
insert into EMPLOYEES (Name, SALARY) values ('KEZA', 5000);

