--Creating table student 
CREATE TABLE STUDENT (
    ID NUMBER,
    NAME VARCHAR(20),
    G CHAR(1) AGE NUMBER;
);

--Inserting data into table
INSERT INTO STUDENT
VALUES(1, 'Nadine', 'F', 12);
INSERT INTO STUDENT
VALUES(2, 'Florent', 'M', 18);
INSERT INTO STUDENT
VALUES(3, 'Laura', 'F', 16);
INSERT INTO STUDENT
VALUES(4, 'Marc', 'M', 20);
INSERT INTO STUDENT
VALUES(4, 'Marc', 'M', 20);
INSERT INTO STUDENT
VALUES(5, 'Claude', 'M', 12);
INSERT INTO STUDENT
VALUES(6, 'John', 'M', 16);