
-- AUDIT STUDENTS TRIGGER
CREATE OR REPLACE TRIGGER AUDIT_ST
BEFORE UPDATE ON STUDENTS
FOR EACH ROW
WHEN (NEW.stu_code <> OLD.stu_code)
DECLARE
COUNTER number;
OLD_CODE VARCHAR(10);
NUM_UP NUMBER;
begin
    SELECT NEW_STU_CODE, N_UPDATED INTO OLD_CODE, NUM_UP FROM AUDIT_TABLE WHERE NEW_STU_CODE = :OLD.STU_CODE;
  IF OLD_CODE = :OLD.STU_CODE THEN
    COUNTER := NUM_UP + 1;
  ELSE
    COUNTER := 1;
  END IF;
    INSERT INTO AUDIT_TABLE VALUES(:OLD.STU_CODE, :NEW.STU_CODE, TO_CHAR(SYSDATE, 'HH24:MI'), COUNTER);
    DBMS_OUTPUT.PUT_LINE('Recorded');
  exception
    when no_data_found then
      COUNTER := 1;
      INSERT INTO AUDIT_TABLE VALUES(:OLD.STU_CODE, :NEW.STU_CODE, TO_CHAR(SYSDATE, 'HH24:MI'), COUNTER);
      DBMS_OUTPUT.PUT_LINE('Recorded');

    when too_many_rows then
      COUNTER := NUM_UP + 1;
      INSERT INTO AUDIT_TABLE VALUES(:OLD.STU_CODE, :NEW.STU_CODE, TO_CHAR(SYSDATE, 'HH24:MI'), COUNTER);
      DBMS_OUTPUT.PUT_LINE('Recorded');
  
end;

-- TEST CASE FOR UPDATING STUDENTS
update STUDENTS
set STU_CODE ='REGNO_02'
WHERE STU_FNAME = 'Rick';
