-- Calling program
declare
NEW_STUDENT STUDENTS%ROWTYPE;
SEARCHED STUDENTS%ROWTYPE;
begin
NEW_STUDENT.STU_CODE := 'REGNO_19';
NEW_STUDENT.STU_FNAME := 'Munezero';
NEW_STUDENT.STU_LNAME := 'Ange';
NEW_STUDENT.STU_AGE := 23;
NEW_STUDENT.STU_ADDRESS := 'Kigalik';
NEW_STUDENT.SPECIALIZATION_ID := 1;
NEW_STUDENT.DEPARTMENT_ID := 1;
NEW_STUDENT.REGISTRATION_DATE:= TO_DATE('2023-04-17','YYYY-MM-DD');

STUD_DETAILS.set_record(NEW_STUDENT);
SEARCHED:= STUD_DETAILS.get_record('REGNO_11');

dbms_output.put_line('His Name is '||SEARCHED.STU_FNAME||' '||SEARCHED.STU_LNAME);
end;
/